# Generated by Django 4.1 on 2022-08-12 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="name",
            new_name="country_name",
        ),
    ]
