# Generated by Django 4.1 on 2022-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0004_alter_country_options_alter_region_options_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("role", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Menus",
            },
        ),
    ]
